/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as mainMainLayoutRouteImport } from './routes/(main)/_mainLayout'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as mainMainLayoutdashboardIndexRouteImport } from './routes/(main)/_mainLayout/(dashboard)/index'

const mainRouteImport = createFileRoute('/(main)')()

const mainRoute = mainRouteImport.update({
  id: '/(main)',
  getParentRoute: () => rootRouteImport,
} as any)
const mainMainLayoutRoute = mainMainLayoutRouteImport.update({
  id: '/_mainLayout',
  getParentRoute: () => mainRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const mainMainLayoutdashboardIndexRoute =
  mainMainLayoutdashboardIndexRouteImport.update({
    id: '/(dashboard)/',
    path: '/',
    getParentRoute: () => mainMainLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof authLoginRoute
  '/': typeof mainMainLayoutdashboardIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof authLoginRoute
  '/': typeof mainMainLayoutdashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)/login': typeof authLoginRoute
  '/(main)': typeof mainRouteWithChildren
  '/(main)/_mainLayout': typeof mainMainLayoutRouteWithChildren
  '/(main)/_mainLayout/(dashboard)/': typeof mainMainLayoutdashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/'
  id:
    | '__root__'
    | '/(auth)/login'
    | '/(main)'
    | '/(main)/_mainLayout'
    | '/(main)/_mainLayout/(dashboard)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authLoginRoute: typeof authLoginRoute
  mainRoute: typeof mainRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(main)': {
      id: '/(main)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof mainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/_mainLayout': {
      id: '/(main)/_mainLayout'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof mainMainLayoutRouteImport
      parentRoute: typeof mainRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/_mainLayout/(dashboard)/': {
      id: '/(main)/_mainLayout/(dashboard)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof mainMainLayoutdashboardIndexRouteImport
      parentRoute: typeof mainMainLayoutRoute
    }
  }
}

interface mainMainLayoutRouteChildren {
  mainMainLayoutdashboardIndexRoute: typeof mainMainLayoutdashboardIndexRoute
}

const mainMainLayoutRouteChildren: mainMainLayoutRouteChildren = {
  mainMainLayoutdashboardIndexRoute: mainMainLayoutdashboardIndexRoute,
}

const mainMainLayoutRouteWithChildren = mainMainLayoutRoute._addFileChildren(
  mainMainLayoutRouteChildren,
)

interface mainRouteChildren {
  mainMainLayoutRoute: typeof mainMainLayoutRouteWithChildren
}

const mainRouteChildren: mainRouteChildren = {
  mainMainLayoutRoute: mainMainLayoutRouteWithChildren,
}

const mainRouteWithChildren = mainRoute._addFileChildren(mainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  authLoginRoute: authLoginRoute,
  mainRoute: mainRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
